#!/usr/bin/env bash

set -o pipefail

[[ "${1}" == *t* ]] && SESSION=tachiyomi || SESSION=aniyomi

NAME=$2
ROOT="$HOME/git/${SESSION}-extensions"

DEFAULT_DIR="${ROOT}/src"

TARGET_DIR=$(compgen -G "${DEFAULT_DIR}/*/${NAME}") # Glob expansion moment

if [[ ! -e "$TARGET_DIR" ]]; then
    echo "Extension ${NAME} does not exist!"
    exit
fi

tmuxCmd(){
    tmux send -t "$SESSION" "${@}" C-m
}

openDir() {
    tmuxCmd "cd ${1}"
}

neww(){
    tmux new-window -t "$SESSION" -n "${@}"
}

splitw(){
    tmux split-window -t "$SESSION"
}

getMainKotlinFile() {
    # Shows only the classname
    className=$(
        grep extClass "$TARGET_DIR/build.gradle" \
            | grep -Eo "\.[A-Z][A-Za-z0-9]+" \
            | cut -d. -f2 \
            | sed "s/Generator//"
    )
    echo "$className.kt"
}

if ! tmux has -t "$SESSION" &> /dev/null; then
    tmux new -s "$SESSION" -n Build -d
        if [[ "$SESSION" == "tachiyomi" ]]; then
            TASK=installDebug
        else
            TASK=assembleDebug
        fi
        EXTPATH="build/outputs/apk/debug/*iyomi*.apk"
        openDir "$TARGET_DIR"
        tmux send -t "$SESSION" "gradle $TASK"
        splitw
            openDir "$TARGET_DIR"
            tmuxCmd "EXTPATH=$EXTPATH"
            if [[ $SESSION == "aniyomi" ]]; then
                tmux send -t "$SESSION" "anitester \$EXTPATH --proxy socks5://localhost:7173"
            fi

    neww editor
        openDir "$TARGET_DIR/src/eu/kanade/tachiyomi/*xtension/*/*"
        tmux send -t "$SESSION" "lvim $(getMainKotlinFile)"

    neww search
        openDir "$DEFAULT_DIR"
        splitw
            openDir "$HOME/git/aniyomi"

    neww testes
        openDir "$HOME/git/teste"
        splitw
            tmux send -t "$SESSION" "scrcpy -S -b8M -m1024 -t --power-off-on-close --no-audio --print-fps"

    neww monitor
        #tmuxCmd "su -c 'top -d 10 -s 3 -o PID,USER,RES,CMDLINE'"
        openDir "$ROOT"
        tmuxCmd mitmproxy
        splitw
            # tmuxCmd "python ~/pidcat xyz.jmir.tachiyomi.mi.debug"
            openDir "$ROOT"
            tmux send -t "$SESSION" "rogcat -p $SESSION"
fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t "$SESSION"
else
    echo "Detach from the current session and attach to $SESSION."
fi
