#!/usr/bin/env bash

[ "${1}" == "t" ] && session=tachiyomi || session=aniyomi

default_dir="$HOME/git/${session}-extensions/src"
target_dir="${default_dir}/*/${2}"

tmuxCmd(){
    tmux send -t $session "${@}" C-m
}

openDir() {
    [ -z $1 ] && tmuxCmd "cd ${target_dir}" || tmuxCmd "cd ${1}"
}

neww(){
    tmux neww -t $session -n $1
}

splitw(){
    tmux splitw -t $session
}

tmux has -t $session &> /dev/null
if [ $? != 0 ]; then
    tmux new -s $session -n Build -d
        openDir
        tmux send -t $session "anitester build/outputs/apk/debug/aniyomi*.apk --proxy socks5://localhost:7173"
        splitw
            openDir
            tmux send -t $session "gradle assembleDebug"

    neww editor
        openDir $target_dir/src/eu/kanade/tachiyomi/*xtension/*/*

    neww search
        openDir $default_dir
        splitw
            openDir $HOME/git/aniyomi/source-api/src/main/java/eu/kanade/tachiyomi/animesource/

    neww testes
        openDir $HOME/git/teste
        # tmux send -t $session "adbcon"
        splitw
            tmux send -t $session "scrcpy -S -b2m -m1024 -t --power-off-on-close"

    neww monitor
        #tmuxCmd "su -c 'top -d 10 -s 3 -o PID,USER,RES,CMDLINE'"
        tmuxCmd mitmproxy
        splitw
            # tmuxCmd "python ~/pidcat xyz.jmir.tachiyomi.mi.debug"
            tmuxCmd "rogcat -N xyz.jmir.tachiyomi.mi.debug"
fi

tmux attach -t $session
