#!/usr/bin/env bash

# DEPENDENCIES: fd, parallel, sed, grep, find and gnu coreutils(for uniq / sort)
getHash(){
    # Ignores the first three lines and calculates the sha1 hash
    local hash=$(tail +3 $1 | sha1sum | cut -d- -f1)

    # if it runs inside src, the names are going to be like <lang>/<extension>,
    # and in multisrc they'll be like <theme/extension>.
    if [[ "$1" == *multisrc* ]]; then
        local name=$(echo $1 | cut -d/ -f3-4)
    else
        local name=$(echo $1 | cut -d/ -f2-3)
    fi
    echo -e "${name}:\t\t${hash}"
}

export -f getHash

fd $1 \
| SHELL=bash parallel getHash \
| sort -k 2 \
| uniq -c -f 1 \
| grep --color=always -P "\s\d+\s"
