#!/usr/bin/bash

# Credits: Vetle (Tachiyomi contributor)
# https://discord.com/channels/349436576037732353/566590778323763207/1142395849922596894
while read -n1 -srp "Press any key to uninstall Aniyomi extensions. ^C to quit. "; do 
    adb shell pm list packages eu.kanade.tachiyomi.animeextension. \
        | cut -d: -f2 \
        | parallel adb uninstall {} 
    echo
done
